### ISSUE TITLE
Weird random looking string at the end of src/lib/courses/programmatic-thinking/programming-concepts/data-structures/enumerations.md

### ISSUE THREAD

**Issue by WhyNotDogie** [lumina-gov/lumina-university#3]
I looked, and i found this at the end of the file:

> ::question{slug="when-to-use-enums" question="Give a specific example of when you would use an enum in a program, and list the variants" context="Incorrect if another type is a more suitable representation, and suggest enum examples if the student is stuck."}

Is this a bug, or a weird markdown feature?

**Comment by AlbertMarashi** [comment]
Indeed, most of these files contain these sorts of questions.

They are used for our AI question assessments feature
<img width="777" alt="image" src="https://github.com/lumina-gov/lumina-university/assets/17972275/78700785-db0e-47a7-a065-ecd8b64c5c58">

Specifically they are markdown directives which are parsed and rendered by our MarkdownRenderer component
